### ISSUE TITLE
Compile errors if I don't import dependent crates such as lazy_static

### ISSUE THREAD

**Issue by gslavin** [dermesser/memoize#9]
When I attempt to use a simple example such as
```
#[memoize]
fn fib(n: i32) -> i32 {
...blah blah
}
```
I get compile errors unless I explicitly import memoize's dependencies (lazy_static, lru, etc) in my Cargo.toml file.
```
error[E0433]: failed to resolve: use of undeclared crate or module `lazy_static`
 --> src/main.rs:3:1
  |
3 | #[memoize(Capacity: 123)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `lazy_static`
  |
```
While I can work around this issue by adding all memoize's dependencies to my Cargo.toml, I feel memoize shouldn't require me to manually specify all its dependencies.

**Comment by dermesser** [comment]
Thank you for complaining! I've finally had the half hour to fix this, which I've been annoyed by too. I was previously not willing to actually split the crate as is required to make this work.

I will be shortly releasing v0.2.0, which contains the fix.

old way:
```toml
[package]
name = "testmemoize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memoize = { version = "0.1.9", features=["full"] }
lazy_static = "1.4"
lru = "0.7"
```

new way:
```toml
[package]
name = "testmemoize"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memoize = { version = "0.2.0", features=["full"] }
```
